### ISSUE TITLE
Cannot debug app from errors shown in the browser's dev console

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/dev-tools#122]
## What should be done 
```console
TypeError: Instance of 'minified:iX': type 'minified:iX' is not a subtype of type 'minified:eP'
main.dart.js:21059     at Object.d (http://localhost:4000/main.dart.js:4802:3)
main.dart.js:21059     at Object.arO (http://localhost:4000/main.dart.js:5411:18)
main.dart.js:21059     at hX.aFV [as a] (http://localhost:4000/main.dart.js:5406:3)
main.dart.js:21059     at na.ub (http://localhost:4000/main.dart.js:59862:6)
main.dart.js:21059     at o0.ud (http://localhost:4000/main.dart.js:62984:58)
main.dart.js:21059     at o0.ed (http://localhost:4000/main.dart.js:62906:3)
main.dart.js:21059     at o0.ed (http://localhost:4000/main.dart.js:63043:3)
main.dart.js:21059     at dT.vo (http://localhost:4000/main.dart.js:62683:3)
main.dart.js:21059     at dT.fP (http://localhost:4000/main.dart.js:62643:16)
main.dart.js:21059     at dT.jy (http://localhost:4000/main.dart.js:62801:32)
```

As we can see above, the code is minified and cannot be easily debugged.

https://stackoverflow.com/questions/59710360/how-to-build-flutter-web-app-in-debug-mode
According to this stackoverflow's thread, we might want to add `--profile --dart-define=Dart2jsOptimization=O0` to the `flutter build web` command in our semantic_release file.

**Comment by taorepoara** [comment]
Resolved with the lenra_cli. You can display the logs of any service.
